name: newpro
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 28.0.1+28

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  share: ^0.6.1+1
  flutter_datetime_picker: ^1.2.1
  datetime_picker_formfield: ^0.1.8
  image_picker:
  http:
  fluttertoast: ^3.0.4
  flutter_date_picker: ^0.1.8
  shared_preferences: ^0.5.3+1
  flutter_range_slider: ^1.4.0
  flutter_launcher_icons: ^0.7.2
  pull_to_refresh: ^1.5.7


  flutter:
    sdk: flutter
  email_validator: '^1.0.0'
  countdown: ^0.1.0
  flutter_circular_chart: ^0.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  material_design_icons_flutter: ^3.2.4096
  carousel_slider: ^1.3.0
  #speech_recognition: ^0.3.0+1
  speech_to_text: ^0.6.2
  flutter_paystack: ^1.0.1
  permission_handler: '^3.3.0'



dev_dependencies:
  flutter_launcher_icons: ^0.7.2+1
  flutter_tts: ^0.2.6

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/icon.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/yu.ttf




  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
